module ShiftsHelper
    def self.large_arrays
        employees = [Employee.find_or_create_by(name: "Juan"), Employee.find_or_create_by(name: "Diego"), Employee.find_or_create_by(name: "Pedro")]
        service = Service.find_or_create_by(name: "Move SPA")
        week = Week.find_or_create_by(number: 02, year: 2021)
        shifts = [
            # Saturday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "07:00:00".to_time, end_time: ("07:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "08:00:00".to_time, end_time: ("08:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "09:00:00".to_time, end_time: ("09:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "10:00:00".to_time, end_time: ("10:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "11:00:00".to_time, end_time: ("11:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "12:00:00".to_time, end_time: ("12:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "13:00:00".to_time, end_time: ("13:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "14:00:00".to_time, end_time: ("14:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "15:00:00".to_time, end_time: ("15:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "16:00:00".to_time, end_time: ("16:00:00".to_time + 1.hour), day: 6),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "17:00:00".to_time, end_time: ("17:00:00".to_time + 1.hour), day: 6),
            # Sunday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "07:00:00".to_time, end_time: ("07:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "08:00:00".to_time, end_time: ("08:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "09:00:00".to_time, end_time: ("09:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "10:00:00".to_time, end_time: ("10:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "11:00:00".to_time, end_time: ("11:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "13:00:00".to_time, end_time: ("13:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "14:00:00".to_time, end_time: ("14:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "15:00:00".to_time, end_time: ("15:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "16:00:00".to_time, end_time: ("16:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "17:00:00".to_time, end_time: ("17:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "18:00:00".to_time, end_time: ("18:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 7),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 7),
            # Monday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 1),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 1),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 1),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 1),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 1),
            # Tuesday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 2),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 2),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 2),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 2),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 2),
            # Wenesday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 3),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 3),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 3),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 3),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 3),
            # Thursday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 4),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 4),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 4),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 4),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 4),
            # Friday
            Shift.create(service_id: service.id, week_id: week.id, start_time: "19:00:00".to_time, end_time: ("19:00:00".to_time + 1.hour), day: 5),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "20:00:00".to_time, end_time: ("20:00:00".to_time + 1.hour), day: 5),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "21:00:00".to_time, end_time: ("21:00:00".to_time + 1.hour), day: 5),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "22:00:00".to_time, end_time: ("22:00:00".to_time + 1.hour), day: 5),
            Shift.create(service_id: service.id, week_id: week.id, start_time: "23:00:00".to_time, end_time: ("23:00:00".to_time + 1.hour), day: 5),
        ]
        {
            employees: employees,
            large_shift_array: shifts,
        large_shift_availabilities: [
            # First employee
                # Saturday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id), 
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
                # Sunday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(0..31)].id),
                # Monday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
                # Tuesday 
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
                # Wenesday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
                # Thursday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
                # Friday
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[0].id, shift_id: shifts[rand(32..51)].id),
            # Second Employee
                # Saturday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id), 
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
                # Sunday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(22..42)].id),
                # Monday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
                # Tuesday 
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
                # Wenesday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
                # Thursday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
                # Friday
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[1].id, shift_id: shifts[rand(0..20)].id),    
            # Third employee
                # Saturday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id), 
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            # Sunday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(0..28)].id),
            # Monday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            # Tuesday 
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            # Wenesday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            # Thursday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            # Friday
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),
            ShiftAvailability.find_or_create_by(employee_id: employees[2].id, shift_id: shifts[rand(30..51)].id),    
            ] }
    end
end
